package views;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;
import main.Start;

/**
 * @author Work
 */

public class AddAlumno extends javax.swing.JFrame {

    public AddAlumno() {
        initComponents();
        this.setSize(320, 230);
        this.setIconImage(getIconImage());
        this.setTitle("Agregar Alumno");
        this.setResizable(false);
        Start.setConteo(Start.getConteo()+1.0f);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLApellido = new javax.swing.JLabel();
        JTFApellido = new javax.swing.JTextField();
        JLNombre = new javax.swing.JLabel();
        JTFNombre = new javax.swing.JTextField();
        JTFAsignatura = new javax.swing.JTextField();
        JTFYearEscolar = new javax.swing.JTextField();
        JTFCurso = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        JSNumero = new JSpinner(new SpinnerNumberModel(1, 1, 75, 1));
        JBAdd = new javax.swing.JButton();
        JLFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLApellido.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JLApellido.setForeground(new java.awt.Color(200, 200, 200));
        JLApellido.setText("Apellido del alumno...");
        JLApellido.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(JLApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 22, 256, 23));

        JTFApellido.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JTFApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JTFApellidoKeyReleased(evt);
            }
        });
        getContentPane().add(JTFApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 264, -1));

        JLNombre.setForeground(new java.awt.Color(200, 200, 200));
        JLNombre.setText("Nombre del alumno...");
        JLNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(JLNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 51, 132, 23));

        JTFNombre.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JTFNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JTFNombreKeyReleased(evt);
            }
        });
        getContentPane().add(JTFNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 140, -1));

        JTFAsignatura.setEditable(false);
        JTFAsignatura.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(JTFAsignatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 264, -1));

        JTFYearEscolar.setEditable(false);
        JTFYearEscolar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JTFYearEscolar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(JTFYearEscolar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 140, -1));

        JTFCurso.setEditable(false);
        JTFCurso.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(JTFCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 264, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Número:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 55, 68, -1));
        getContentPane().add(JSNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 50, 50, 28));

        JBAdd.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        JBAdd.setText("Agregar");
        getContentPane().add(JBAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 140, -1, -1));

        JLFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/imagenes/fondoPrincipal.jpg"))); // NOI18N
        getContentPane().add(JLFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 307, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTFApellidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFApellidoKeyReleased
        if(JTFApellido.getText().isEmpty()) JLApellido.setVisible(true);
        else JLApellido.setVisible(false);
    }//GEN-LAST:event_JTFApellidoKeyReleased

    private void JTFNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFNombreKeyReleased
        if(JTFNombre.getText().isEmpty())   JLNombre.setVisible(true);
        else    JLNombre.setVisible(false);
    }//GEN-LAST:event_JTFNombreKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton JBAdd;
    private javax.swing.JLabel JLApellido;
    private javax.swing.JLabel JLFondo;
    private javax.swing.JLabel JLNombre;
    public javax.swing.JSpinner JSNumero;
    public javax.swing.JTextField JTFApellido;
    public javax.swing.JTextField JTFAsignatura;
    public javax.swing.JTextField JTFCurso;
    public javax.swing.JTextField JTFNombre;
    public javax.swing.JTextField JTFYearEscolar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

     @Override
    public Image getIconImage(){
        Image img = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("views/imagenes/myLogo.png"));
        return img;
    }
    
    
    public void resetComponent(){
        JTFApellido.setText("");
        JTFNombre.setText("");
        JSNumero.setValue(JSNumero.getNextValue());
        JLApellido.setVisible(true);
        JLNombre.setVisible(true);
    }
}
