package views;

import controllers.singletons.Singleton_Controllers;
import controllers.singletons.Singleton_Interfaces;
import java.awt.Color;
import java.awt.Frame;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import main.Start;

/**
 * @author Work-Game
 */

public class AddIndicadorLogro extends javax.swing.JDialog {
    Singleton_Controllers s_c;
    Singleton_Interfaces s_i;
    
    public AddIndicadorLogro(Frame parent, Boolean modal) {
        super(parent, modal);
        initComponents();
        this.setIconImage(getIconImage());
        this.setTitle("Agregar Indicadores De Logro");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        eventCloseWindow();
        //size 600x290
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JLIndicadorArea = new javax.swing.JLabel();
        JLUnidad = new javax.swing.JLabel();
        JTFUnidad = new javax.swing.JTextField();
        JBUnidad = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTACompetencia = new javax.swing.JTextArea();
        JBIndicador = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTAIndicador = new javax.swing.JTextArea();
        JBTema = new javax.swing.JButton();
        JLTema = new javax.swing.JLabel();
        JTFTema = new javax.swing.JTextField();
        JCmbPeriodo = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        JLFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLIndicadorArea.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        JLIndicadorArea.setForeground(new java.awt.Color(200, 200, 200));
        JLIndicadorArea.setText("jLabel1");
        jPanel1.add(JLIndicadorArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 270, -1));

        JLUnidad.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JLUnidad.setForeground(new java.awt.Color(150, 150, 150));
        JLUnidad.setText("Unidad...");
        jPanel1.add(JLUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 20, 225, 26));

        JTFUnidad.setEditable(false);
        JTFUnidad.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel1.add(JTFUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 230, -1));

        JBUnidad.setText("...");
        JBUnidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBUnidadActionPerformed(evt);
            }
        });
        jPanel1.add(JBUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 32, 18));

        JTACompetencia.setEditable(false);
        JTACompetencia.setColumns(20);
        JTACompetencia.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JTACompetencia.setForeground(new java.awt.Color(150, 150, 150));
        JTACompetencia.setRows(5);
        JTACompetencia.setText("Competencia...");
        jScrollPane1.setViewportView(JTACompetencia);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 270, 170));

        JBIndicador.setText("...");
        JBIndicador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBIndicadorActionPerformed(evt);
            }
        });
        jPanel1.add(JBIndicador, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 240, 33, 18));

        JTAIndicador.setEditable(false);
        JTAIndicador.setColumns(20);
        JTAIndicador.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JTAIndicador.setForeground(new java.awt.Color(150, 150, 150));
        JTAIndicador.setRows(5);
        JTAIndicador.setText("Indicador de logro...");
        jScrollPane2.setViewportView(JTAIndicador);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 270, 170));

        JBTema.setText("...");
        JBTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTemaActionPerformed(evt);
            }
        });
        jPanel1.add(JBTema, new org.netbeans.lib.awtextra.AbsoluteConstraints(545, 240, 35, 18));

        JLTema.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JLTema.setForeground(new java.awt.Color(150, 150, 150));
        JLTema.setText("Tema...");
        jPanel1.add(JLTema, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 277, 555, 23));

        JTFTema.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JTFTema.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTFTemaFocusLost(evt);
            }
        });
        JTFTema.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JTFTemaKeyReleased(evt);
            }
        });
        jPanel1.add(JTFTema, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 275, 560, -1));

        JCmbPeriodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Periodos :", "Periodo 1", "Periodo 2", "Periodo 3", "Periodo 4" }));
        jPanel1.add(JCmbPeriodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 315, 90, -1));

        jButton1.setText("Agregar");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 315, -1, -1));

        JLFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/imagenes/fondoPrincipal.jpg"))); // NOI18N
        jPanel1.add(JLFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 360));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBUnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBUnidadActionPerformed
        Start.identificador = 2;
        s_c = Singleton_Controllers.getInstance();
        s_i = Singleton_Interfaces.getInstance();
        s_c.add_select.cargador();
        s_i.add_select.JTFCurso.setEditable(true);
        s_i.add_select.JLCurso.setEnabled(true);
        s_i.add_select.JLTitulo.setText("Seleccione su unidad");
        s_i.add_select.JLAgregar.setText("Agregar Unidad");
        s_i.add_select.JLCurso.setText("Escribir Unidad...");
        s_i.add_select.JLAsignatura.setText("No Disponible...");
        s_i.add_select.enabledComponents(false);
        s_i.add_select.JBAdd.setEnabled(true);
        s_i.add_select.setVisible(true);
    }//GEN-LAST:event_JBUnidadActionPerformed

    private void JBIndicadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBIndicadorActionPerformed
        s_i = Singleton_Interfaces.getInstance();
        s_c = Singleton_Controllers.getInstance();
        Start.identificador = -3;
        s_c.principal.setSeccion(-1);
        s_i.indicador_Logro.JComboBPerriodos.setEnabled(false);
        s_i.indicador_Logro.JLIndicador.setText("Seleccione su Competencia");
        s_i.indicador_Logro.JBAdd.setEnabled(false);
        s_i.indicador_Logro.JBSelect.setText("Seleccionar");
        s_i.indicador_Logro.JBSelect.setEnabled(true);
        s_i.indicador_Logro.JTAVista.setEditable(true);
        s_c.indicadores.cargador((byte)0);
        s_i.indicador_Logro.setVisible(true);
    }//GEN-LAST:event_JBIndicadorActionPerformed

    private void JBTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTemaActionPerformed
        s_i = Singleton_Interfaces.getInstance();
        s_c = Singleton_Controllers.getInstance();
        Start.identificador = 9;
        s_c.principal.setSeccion(-1);
        s_c.indicadores.i = false;
        s_i.indicador_Logro.JComboBPerriodos.setEnabled(false);
        s_i.indicador_Logro.JLIndicador.setText("Seleccione su Indicador");
        s_i.indicador_Logro.JBAdd.setEnabled(false);
        s_i.indicador_Logro.JBSelect.setText("Seleccionar");
        s_i.indicador_Logro.JBSelect.setEnabled(true);
        s_i.indicador_Logro.JTAVista.setEditable(true);
        s_c.indicadores.cargador((byte)0);
        s_i.indicador_Logro.setVisible(true);
    }//GEN-LAST:event_JBTemaActionPerformed

    private void JTFTemaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFTemaKeyReleased
        if (JTFTema.getText().isEmpty()) JLTema.setVisible(true);
        else JLTema.setVisible(false);
    }//GEN-LAST:event_JTFTemaKeyReleased

    private void JTFTemaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFTemaFocusLost
        if (JTFTema.getText().isEmpty()) JLTema.setVisible(true);
        else JLTema.setVisible(false);
    }//GEN-LAST:event_JTFTemaFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBIndicador;
    private javax.swing.JButton JBTema;
    public javax.swing.JButton JBUnidad;
    public javax.swing.JComboBox<String> JCmbPeriodo;
    private javax.swing.JLabel JLFondo;
    public javax.swing.JLabel JLIndicadorArea;
    private javax.swing.JLabel JLTema;
    public javax.swing.JLabel JLUnidad;
    public javax.swing.JTextArea JTACompetencia;
    public javax.swing.JTextArea JTAIndicador;
    public javax.swing.JTextField JTFTema;
    public javax.swing.JTextField JTFUnidad;
    public javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    private void eventCloseWindow(){
        this.addWindowListener(new WindowAdapter(){
            @Override
            public void windowClosing(WindowEvent e) {
                resetComponents();
            }
        });
    }
    
    public Image getIconImage(){
        Image img = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("views/imagenes/myLogo.png"));
        return img;
    }
    
    public void resetComponents(){
        JTFUnidad.setText("");
        JLUnidad.setVisible(true);
        JTACompetencia.setText("Competencia...");
        JTACompetencia.setForeground(new Color(150,150,150));
        JTAIndicador.setText("Indicador de logro...");
        JTAIndicador.setForeground(new Color(150,150,150));
        JTFTema.setText("");
        JLTema.setVisible(true);
        JCmbPeriodo.setSelectedIndex(0);
    }
}
