/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.singletons.Singleton_Interfaces;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import main.Start;
import java.util.logging.*;

/**
 *
 * @author Work
 */
public class Carga extends javax.swing.JDialog {
    private Thread hilo_contenedor;
    private Singleton_Interfaces interfaces = null;
    
    public Carga(Thread hilo) {
        initComponents();
        this.setSize(498, 127);
        this.setLocationRelativeTo(null);
        hilo_contenedor = hilo;
        interfaces = Singleton_Interfaces.getInstance();
        new Thread(hilo_contenedor).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/imagenes/myLogo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 20, 60, 50));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void paint(Graphics g){
        super.paint(g);
        GradientPaint gp = new GradientPaint(96, 127, Color.BLUE, 498, 127, Color.RED);
        Graphics2D g2d = (Graphics2D) g;
        g2d.setPaint(gp);
        if(Start.identificador == 0){
            interfaces.add_select.initVariables();
            interfaces.add_select.JLAgregar.setText("Agregar un nuevo curso");
        }
        while (Start.isCargando()) {     
            //System.out.println("pasa con exito.. conte: "+Start.getConteo()+" maxconteo: "+Start.maxConteo);
            float porsentaje = (Start.getConteo() / Start.getMaxConteo());
            g2d.fillRect(0, 112, (int)(porsentaje*498), 127);
        }
        try {
            hilo_contenedor.join(0);
            this.dispose();
            if(Start.identificador == 0)interfaces.add_select.setVisible(true);
        } catch (InterruptedException ex) {
            interfaces.registro_error.registrarError(Level.SEVERE, "Nuevo error detectado al completar "
                                                            + "la carga o cerrar el hilo de carga\n");
            interfaces.registro_error.registrarError(Level.SEVERE, RegistroError.getStackTrace(ex));
        }
    }
}
