/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.singletons.Singleton_Controllers;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import main.Start;

/**
 *
 * @author Work
 */
public class IndicadoresLogro extends javax.swing.JFrame {
    Singleton_Controllers controladores;
    
    public IndicadoresLogro() {
        initComponents();
        this.setSize(800,300);
        this.setIconImage(getIconImage());
        this.setTitle("Indicadores de logro");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        scroll_tabla.setVisible(false);
        closing();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JComboBPerriodos = new javax.swing.JComboBox<>();
        JLIndicador = new javax.swing.JLabel();
        JBAdd = new javax.swing.JButton();
        JBSelect = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTAVista = new javax.swing.JTextArea();
        scroll_tabla = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        JLFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JComboBPerriodos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Periodos", "Periodo 1", "Periodo 2", "Periodo 3", "Periodo 4" }));
        JComboBPerriodos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(JComboBPerriodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 90, -1));

        JLIndicador.setFont(new java.awt.Font("Palatino Linotype", 0, 14)); // NOI18N
        JLIndicador.setForeground(new java.awt.Color(230, 230, 230));
        JLIndicador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLIndicador.setText("Seleccione...");
        jPanel1.add(JLIndicador, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 190, 30));

        JBAdd.setText("Agregar");
        JBAdd.setEnabled(false);
        jPanel1.add(JBAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        JBSelect.setText("Sleccionar");
        JBSelect.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(JBSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 20, -1, -1));

        JTAVista.setEditable(false);
        JTAVista.setColumns(20);
        JTAVista.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JTAVista.setRows(5);
        jScrollPane1.setViewportView(JTAVista);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(458, 10, 320, 245));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        scroll_tabla.setViewportView(jTable1);

        jPanel1.add(scroll_tabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 440, 195));

        JLFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/imagenes/fondoPrincipal.jpg"))); // NOI18N
        jPanel1.add(JLFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 270));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row = jTable1.getSelectedRow();
        controladores = Singleton_Controllers.getInstance();
        if(controladores.principal.getSeccion() == 2){
            JTAVista.setText("Competencia:\n\n"+jTable1.getValueAt(row, 1).toString()+"\n\nIndicador:\n\n"+
                             jTable1.getValueAt(row, 2).toString());
        }else if(Start.identificador == 8){
            
        }
        else    JTAVista.setText(jTable1.getValueAt(row, 0).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton JBAdd;
    public javax.swing.JButton JBSelect;
    public javax.swing.JComboBox<String> JComboBPerriodos;
    private javax.swing.JLabel JLFondo;
    public javax.swing.JLabel JLIndicador;
    public javax.swing.JTextArea JTAVista;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    public javax.swing.JScrollPane scroll_tabla;
    // End of variables declaration//GEN-END:variables

    public void resetComponentes(){
        JComboBPerriodos.setSelectedIndex(0);
        scroll_tabla.setVisible(false);
        JTAVista.setText("");        
    }
    
    private void closing(){
        this.addWindowListener(new WindowAdapter(){
            @Override
            public void windowClosing(WindowEvent we){
                resetComponentes();
            }
        });
    }
    
    @Override
    public Image getIconImage(){
        Image img = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("views/imagenes/myLogo.png"));
        return img;
    }
    
}
