package views;

import controllers.singletons.Singleton_Controllers;
import java.awt.Frame;
import java.awt.Image;
import java.awt.MenuItem;
import java.awt.PopupMenu;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.DefaultListModel;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.ListModel;

/**
 * @author Work
 */

public class Registros_Personal extends javax.swing.JDialog {
    DefaultListModel model1;
    JPopupMenu click_derecho;
    
    Singleton_Controllers controladores;
        
    public Registros_Personal(Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setSize(515, 315);
        this.setIconImage(getIconImage());
        this.setTitle("Agregar Registro Personal");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        model1 = new DefaultListModel();
        click_derecho = new JPopupMenu("Menu");
        fillpopumenu();
        eventCloseWindow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        JLAddCalificador = new javax.swing.JLabel();
        JTFAddCalificador = new javax.swing.JTextField();
        JBAddCalificador = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JListCalificadores = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        JListTemas = new javax.swing.JList<>();
        JBAddRegistro = new javax.swing.JButton();
        JLFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Calificador de R.P." }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 140, -1));

        JLAddCalificador.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JLAddCalificador.setForeground(new java.awt.Color(170, 170, 170));
        JLAddCalificador.setText("Agregar calificador a la lista de R.P.");
        JLAddCalificador.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        JLAddCalificador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLAddCalificadorMouseClicked(evt);
            }
        });
        jPanel1.add(JLAddCalificador, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 23, 213, 21));

        JTFAddCalificador.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JTFAddCalificador.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTFAddCalificadorFocusLost(evt);
            }
        });
        JTFAddCalificador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JTFAddCalificadorKeyReleased(evt);
            }
        });
        jPanel1.add(JTFAddCalificador, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 220, -1));

        JBAddCalificador.setText("Agregar");
        JBAddCalificador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JBAddCalificador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAddCalificadorActionPerformed(evt);
            }
        });
        jPanel1.add(JBAddCalificador, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, -1, -1));

        JListCalificadores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JListCalificadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                JListCalificadoresMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(JListCalificadores);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 140, 200));

        JListTemas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        JListTemas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane2.setViewportView(JListTemas);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 311, 165));

        JBAddRegistro.setText("Registrar");
        JBAddRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(JBAddRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 232, -1, -1));

        JLFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/imagenes/fondoPrincipal.jpg"))); // NOI18N
        jPanel1.add(JLFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 280));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JLAddCalificadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLAddCalificadorMouseClicked
        JTFAddCalificador.grabFocus();
    }//GEN-LAST:event_JLAddCalificadorMouseClicked

    private void JTFAddCalificadorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFAddCalificadorKeyReleased
        if(JTFAddCalificador.getText().isEmpty()) JLAddCalificador.setVisible(true);
        else JLAddCalificador.setVisible(false);
    }//GEN-LAST:event_JTFAddCalificadorKeyReleased

    private void JBAddCalificadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAddCalificadorActionPerformed
        if(!JTFAddCalificador.getText().isEmpty()){
            model1.addElement(JTFAddCalificador.getText());
            JListCalificadores.setModel(model1);
        }
        
    }//GEN-LAST:event_JBAddCalificadorActionPerformed

    private void JTFAddCalificadorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFAddCalificadorFocusLost
        if(JTFAddCalificador.getText().isEmpty()) JLAddCalificador.setVisible(true);
    }//GEN-LAST:event_JTFAddCalificadorFocusLost

    private void JListCalificadoresMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JListCalificadoresMouseReleased
         ListModel l = JListCalificadores.getModel();
        if(evt.isPopupTrigger() && l.getSize() != 0 && l.getSize() != -1){
            JListCalificadores.setSelectedIndex(JListCalificadores.locationToIndex(evt.getPoint()));
            click_derecho.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_JListCalificadoresMouseReleased

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        if(jComboBox1.getSelectedItem() != null){
            if(!jComboBox1.getSelectedItem().toString().equals("Calificador de R.P.")){
                model1.addElement(jComboBox1.getSelectedItem());
                JListCalificadores.setModel(model1);
            }
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBAddCalificador;
    public javax.swing.JButton JBAddRegistro;
    private javax.swing.JLabel JLAddCalificador;
    private javax.swing.JLabel JLFondo;
    public javax.swing.JList<String> JListCalificadores;
    public javax.swing.JList<String> JListTemas;
    private javax.swing.JTextField JTFAddCalificador;
    public javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    private void eventCloseWindow(){
        this.addWindowListener(new WindowAdapter(){
            @Override
            public void windowClosing(WindowEvent e) {
                resetComponents((byte)0);
            }
        });
    }
    
    private void fillpopumenu(){
        JMenuItem eliminar = new JMenuItem("Eliminar");
        eliminar.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent ae){
                int index = JListCalificadores.getSelectedIndex();
                model1.remove(index);
            }
        });
        click_derecho.add(eliminar);
    }
    
    public Image getIconImage(){
        Image img = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("views/imagenes/myLogo.png"));
        return img;
    }
    
    
    public void resetComponents(byte indicacion){
        jComboBox1.removeAllItems();
        jComboBox1.addItem("Calificador de R.P.");
        JTFAddCalificador.setText("");
        JLAddCalificador.setVisible(true);
        /*model1.clear();
        JListCalificadores.setModel(model1);*/
        if(indicacion > 0){
            controladores = Singleton_Controllers.getInstance();
            controladores.addRegistro_Personal.cargarParametro();
            controladores.addRegistro_Personal.cargarTema();
        }
    }
}
